server:
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 1800
        http-only: true # js in browser cant read the cookie
        secure: false #This means the browser is allowed to send the cookie over HTTP as well as HTTPS.


jwt:
  secret: this-is-a-temporary-dev-secret-change-it-later-make-it-long
  algorithm:  HS256    # or RS256 , HS256
  access-token-expiry:  900000
  refresh-token-expiry: 604800000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

webauthn:
  rp-id: localhost
  allowed-origins: http://localhost:8080

myauth:
  test-user:
    enabled: true

rate-limit:
  requests-per-minute: 5
  window-seconds: 60